#!/bin/bash

export CLUSTER_SSHKEY=$(cat ~/.ssh/id_ed25519_hlab.pub)
export PULL_SECRET=$(cat pull_secret.txt | jq -R .)
cat << EOF > ./deployment-sno.json
{
  "kind": "Cluster",
  "name": "ocpd",  
  "openshift_version": "4.8",
  "ocp_release_image": "quay.io/openshift-release-dev/ocp-release:4.8.5-x86_64",
  "base_dns_domain": "lab.local",
  "hyperthreading": "all",
  "ingress_vip": "192.167.124.8",
  "schedulable_masters": false,
  "high_availability_mode": "None",
  "user_managed_networking": false,
  "platform": {
    "type": "baremetal"
   },
  "cluster_networks": [
    {
      "cidr": "10.128.0.0/14",
      "host_prefix": 23
    }
  ],
  "service_networks": [
    {
      "cidr": "172.31.0.0/16"
    }
  ],
  "machine_networks": [
    {
      "cidr": "192.168.1.0/25"
    }
  ],
  "network_type": "OVNKubernetes",
  "additional_ntp_source": "ntp1.hetzner.de",
  "vip_dhcp_allocation": false,      
  "ssh_public_key": "$CLUSTER_SSHKEY",
  "pull_secret": $PULL_SECRET
}
EOF